name = "axis-mock"
main = ".open-next/worker.js" # OpenNextを使っている場合
compatibility_date = "2024-09-23"

[build]
command = "npx @opennextjs/cloudflare build"

pages_build_output_dir = ".open-next/assets"